### ISSUE TITLE
Google login method

### ISSUE THREAD

**Issue by rediz** [argrento/huami-token#1]
If im not mistaken this won't work with Google accounts? I have made/logged in with Google account in Mi Fit -app and now that i ran the python script the login page doesn't have option to login with google so reqular Mi Account is required to run this?

Also sorry if this is noobish info, but I ran this in linux and that for I had to specify python version to run this. Reqular python huami_token.py gave syntax error, but running python3.7 it worked perfectly.

**Comment by argrento** [comment]
Unfortunately, Google login is not supported. Only login with Mi and Amazfit accounts can be used. 
As a workaround, you can remove your device from your account and create a new Amazfit account, which will use email and password. Than add your device to this new account. In this case you can use this script and will get auth key. _Be carefyl, because you can loose your current day stats._

According to python version, thank you to pointing this out, I will change the readme.

**Comment by rediz** [comment]
Thanks for your reply. I was also able to combine accounts let both google and Mi account be logged on same app, which in return I was able to use the script to get my auth-key.
